/*
This file was auto-generated by mupdfwrap.py.
*/

#ifndef MUPDF_INTERNAL_H
#define MUPDF_INTERNAL_H


namespace mupdf
{

/* Internal use only. Returns fz_context* for use by current thread. */
fz_context* internal_context_get();



} /* End of namespace mupdf. */

#endif
